#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author : Sedate

class CMSList(object):
    cms_list = {
        'content="WordPress': 'WordPress',
        'wp-includes': 'WordPress',
        'pma_password': 'phpMyAdmin',
        'Powered by&http://www.phpcms.cn': 'PhpCMS',
        'content=\"Phpcms': 'PhpCMS',
        'Powered by Phpcms': 'PhpCMS',
        'data/config.js': 'PhpCMS',
        'Power by DedeCms': 'DedeCMS',
        'Powered by&http://www.dedecms.com/': 'DedeCMS',
        '/templets/default/style/dedecms.css': 'DedeCMS',
        'NewsClass.asp?BigClass=企业新闻': '南方良精',
        'HrDemand.asp': '南方良精',
        'Aboutus.asp?Title=企业简介': '南方良精',
        'content="Templet360': 'Templet360',
        'AdaptCMS': 'AdaptCMS',
        'TUTUCMS': 'tutucms',
        'Powered by TUTUCMS': 'tutucms',
        'Powered by 1024 CMS': '1024 CMS',
        '1024 CMS (c)': '1024 CMS',
        'Publish By JCms2010': '捷点 JCMS',
        'webEdition': 'webEdition',
        'Powered by phpshe': 'phpshe',
        'phpshe': 'phpshe',
        '/theme/2009/image&login.asp': '北京清科锐华CEMIS',
        'css/25yi.css': '25yi',
        'Powered by 25yi': '25yi',
        '/bundles/oroui/': 'oroCRM',
        'Powered by SeaCms': '海洋CMS',
        'seacms': '海洋CMS',
        '/images/v7/cms.css': 'qibosoft v7',
        'opac_two': '北创图书检索系统',
        'dayrui/statics': 'dayrui系列CMS',
        'upload/moban/images/style.css': 'ASP168 欧虎',
        'default.php?mod=article&do=detail&tid': 'ASP168 欧虎',
        'Powered by FineCMS': 'FineCMS',
        'dayrui@gmail.com': 'FineCMS',
        'FineCMS': 'FineCMS',
        'ASPCMS': 'ASPCMS',
        '/index.php/clasify/showone/gtitle/': 'O2OCMS',
        'CmsEasy': 'CmsEasy',
        'damicms': '大米CMS', '大米CMS': '大米CMS',
        '/Include/EcsServerApi.js': '易创思ecs',
        'Osclass': 'Osclass',
        'm_ctr32': 'IdeaCMS',
        'Powered By IdeaCMS': 'IdeaCMS',
        'bit-xxzs': 'Bit',
        'xmlpzs/webissue.asp': 'Bit',
        '/css/mymps.css': 'mymps',
        'mymps': 'mymps',
        'ycportal/webpublish': '全国烟草系统',
        'bx_css_async': 'Dolphin',
        '/tpl/Home/weimeng/common/css/': '微门户',
        'DianCMS_用户登陆引用': '易点CMS',
        'DianCMS_SiteName': '易点CMS',
        'r/cms/www': 'unknown cms rcms',
        '技术支持：云因信息': 'yunyin',
        'PDV_PAGENAME': 'PHPWEB',
        'Author" content="微普外卖点餐系统': '微普外卖点餐系统',
        'Powered By 点餐系统': '微普外卖点餐系统',
        'userfiles/shoppics/': '微普外卖点餐系统',
        'content="jieqi cms': 'jieqi',
        'Powerd by AppCMS': 'appcms',
        'content="OURPHP': 'ourphp',
        'Powered by ourphp': 'ourphp',
        'content="eAdmin': 'eadmin',
        'content="EasyAdmin': 'EasyAdmin',
        'Powered by FengCms': 'fengcms',
        'content="FengCms': 'fengcms',
        'content="DotNetNuke': 'DotNetNuke',
        'content=",DotNetNuke': 'DotNetNuke',
        'Created by DotNetCMS': 'Foosun',
        'For Foosun': 'Foosun',
        'Powered by www.Foosun.net,Products:Foosun Content Manage system': 'Foosun',
        '/deptWebsiteAction.do': '某通用型政府cms',
        'Powered by wuzhicms': 'wuzhicms',
        'content="wuzhicms': 'wuzhicms',
        '_files/jspxcms.css': 'Jspxcms',
        'NITC Web Marketing Service': 'NITC',
        '/images/nitc1.png': 'NITC',
        'reader/view_abstract.aspx': 'E-Tiller',
        'content="IMGCMS': 'IMGCms',
        'Powered by IMGCMS': 'IMGCms',
        '/r/cms/www/': 'RCMS',
        'jhtml': 'RCMS',
        '/js/jtbc.js': 'JTBC(CMS)',
        'content="JTBC': 'JTBC(CMS)',
        'Powered by TurboCMS': 'TurboCMS',
        '/cmsapp/zxdcADD.jsp': 'TurboCMS',
        '/cmsapp/count/newstop_index.jsp?siteid=': 'TurboCMS',
        "本系统由:'中国期刊先知网',": "中国期刊先知网",
        '/js/jPackageCss/jPackage.css': '贷齐乐p2p',
        'src="/js/jPackage': '贷齐乐p2p',
        'generator" content="Typecho': 'Typecho',
        '强力驱动&Typecho': 'Typecho',
        'content="BageCMS': '八哥CMS',
        'content="动力启航,DTCMS': 'dtcms',
        'keyicms：keyicms': '科蚁CMS',
        'web980': 'DIYWAP',
        'bannerNum': 'DIYWAP',
        'generator" content="Plone': 'plone',
        'app/Tpl/fanwe_1/images/lazy_loading.gif&index.php?ctl=article_cate': '方维众筹',
        'css/css_whir.css': '万户网络',
        'wsite-page-index': 'weebly',
        'content="niubicms': '牛逼cms',
        '/Widgets/WidgetCollection/': 'We7',
        '/css/yxcms.css': 'Yxcms',
        'content="Yxcms': 'Yxcms',
        'Powered by Diferior': 'Diferior',
        'Powered by PHPVOD': 'phpvod',
        'content="phpvod': 'phpvod',
        'Dolibarr Development Team': 'Dolibarr',
        'Telerik.Web.UI.WebResource.axd': 'Telerik Sitefinity',
        'content="Sitefinity': 'Telerik Sitefinity',
        'main/building.cfm': '云因网上书店',
        'href="../css/newscomm.css': '云因网上书店',
        'content="tipask': 'Tipask',
        'yidacms.css': 'yidacms',
        'advfile/ad12.js': 'XYCMS',
        'powerd by&BEESCMS': 'beeCMS',
        'template/default/images/slides.min.jquery.js': 'beeCMS',
        'Powered by ESPCMS': 'ESPCMS',
        'infolist_fff&/templates/default/style/tempates_div.css': 'ESPCMS',
        'webplus': 'webplus', '高校网站群管理平台': 'webplus',
        'content="WeiPHP': 'weiphp',
        '/css/weiphp.css': 'weiphp',
        'publish by BoyowCMS': 'BoyowCMS',
        'generator" content="ezCMS': 'concrete5',
        'CCM_DISPATCHER_FILENAME': 'concrete5',
        '凡科互联网科技股份有限公司': '凡科建站',
        'content="凡科': '凡科建站',
        '/css/cmstop-common.css': 'CMSTop',
        '/js/cmstop-common.js': 'CMSTop',
        'cmstop-list-text.css': 'CMSTop',
        'Powered by Adxstudio': 'ADXStudio',
        'poweredbyadx.png': 'ADXStudio',
        'Powered by DouPHP': 'DouPHP',
        'controlBase&indexLeft': 'DouPHP',
        'content="MetInfo': 'MetInfo',
        'powered_by_metinfo': 'MetInfo',
        '/images/css/metinfo.css': 'MetInfo',
        'chanzhi.js': 'chanzhi',
        'content="Drupal': 'Drupal',
        'jQuery.extend\(Drupal.settings': 'Drupal',
        'ace-drupal7prod&/sites/all/themes/': 'Drupal',
        'Powered By PHPB2B': 'phpb2b',
        'SiteServer CMS&http://www.siteserver.cn': 'SiteServer',
        'T_系统首页模板': 'SiteServer',
        'siteserver&sitefiles': 'SiteServer',
        'JEECMS&Powered by': 'JEECMS',
        'script src=http://www.2cto.com/uploadfile/2017/0329/20170329015648125.cn/&': '逐浪zoomla',
        'Powered by Phpmps': 'phpmps',
        'templates/phpmps/style/index.css': 'phpmps',
        'Powered by Dswjcms': 'dswjcms',
        'content="Dswjcms': 'dswjcms',
        'maccms:voddaycount': '苹果CMS',
        'content="PageAdmin CMS': 'PageAdmin',
        '/e/images/favicon.ico': 'PageAdmin',
        '_ZCMS_ShowNewMessage': 'ZCMS',
        'zcms_skin': 'ZCMS',
        'ZCMS泽元内容管理': 'ZCMS',
        'lan12-jingbian-hong': '易普拉格科研管理系统',
        '科研管理系统，北京易普拉格科技': '易普拉格科研管理系统',
        '/ks_inc/common.js': 'KesionCMS',
        'publish by KesionCMS': 'KesionCMS',
        'Produced By 大汉网络': '大汉系统(Hanweb)',
        '\'http://www.hanweb.com\' style=\'display:none\'>': '大汉系统(Hanweb)',
        '\'Generator\' content=\'大汉版通\'>': '大汉系统(Hanweb)',
        '\'Author\' content=\'大汉网络\'>': '大汉系统(Hanweb)',
        '/jcms_files/jcms': '大汉系统(Hanweb)',
        'bigSortProduct.asp?bigid': '北京阳光环球建站系统',
        'content="NIUCMS': 'niucms',
        'index.php\?ac=link_more&index.php\?ac=news_list': 'TCCMS',
        'publico/template/&zonapie': '360webfacil 360WebManager',
        '360WebManager Software': '360webfacil 360WebManager',
        'labelOppInforStyle': '地平线CMS',
        'search_result.aspx&frmsearch': '地平线CMS',
        'FoxPHPScroll': 'FoxPHP',
        'FoxPHP_ImList': 'FoxPHP',
        'content="FoxPHP': 'FoxPHP',
        'var webroot=': 'sdcms',
        '/js/sdcms.js': 'sdcms',
        '/wcm/app/js': 'TRS WCM',
        '0;URL=/wcm': 'TRS WCM',
        'window.location.href = "//wcm";': 'TRS WCM',
        'forum\.trs\.com\.cn&wcm': 'TRS WCM',
        '/wcm" target="_blank': 'TRS WCM',
        '/wcm" target="_blank">管理': 'TRS WCM',
        '/templates/default/css/common.css&selectjobscategory': '74cms',
        'content="74cms.com': '74cms',
        'content="骑士CMS': '74cms',
        'Generator" content="2z project': '2z project',
        'generator" content="MediaWiki': 'MediaWiki',
        '/wiki/images/6/64/Favicon.ico': 'MediaWiki',
        'Powered by MediaWiki': 'MediaWiki',
        '/app/home/skins/default/style.css': 'ThinkSAAS',
        'content="Joomla': 'Joomla',
        '/media/system/js/core\.js&/media/system/js/mootools-core\.js': 'Joomla',
        'phpMyWind.com All Rights Reserved': 'PHPMyWind',
        'content="PHPMyWind': 'PHPMyWind',
        'semcms PHP': 'SEMcms',
        'sc_mid_c_left_c sc_mid_left_bt': 'SEMcms',
        '/Template/Ant/Css/AntHomeComm\.css': '小蚂蚁',
        'content="171cms': '171cms',
        'content="BAOCMS': 'baocms',
        'infoglueBox.png': 'infoglue',
        'power by bcms': 'bluecms',
        'bcms_plugin': 'bluecms',
        'content="MoMoCMS': 'MoMoCMS',
        'Powered BY MoMoCMS': 'MoMoCMS',
        '/css/global\.css&/twcms/theme/': 'TWCMS',
        'content="emlog"': 'Emlog',
        'GB_ROOT_DIR&maincontent.css': 'HIMS 酒店云计算服务',
        'HIMS酒店云计算服务': 'HIMS 酒店云计算服务',
        'GENERATOR" content="EasySite': 'Easysite',
        'Copyright 2009 by Huilan': 'Easysite',
        '_DesktopModules_PictureNews': 'Easysite',
        '页面加载中,请稍候&FrontEnd': '国家数字化学习资源中心系统'
    }
